define([
	'./HomeController',
	'./LoginController',
	'./SignupController',
	'./MainController',
	'./GroupController',
	'./IndividualGroupController',
	'./ComplaintBoxController',
	'./GroupCalendarController',
	'./GroupChatController',
	'./AddEventDialogController',
	'./EditEventDialogController',
	'./ComplaintBoxController',
	'./StartDoodleDialogController',
	'./ScheduleAssistantDialogController',
], function () {});
